name: Publication sur Docker Hub

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Compilation vers image Docker
        run: sudo docker build -t dimitridr/yaot:$GITHUB_SHA .

      - name: Étiquetage « latest » sur image produite
        run: docker tag dimitridr/yaot:$GITHUB_SHA dimitridr/yaot:latest

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publication sur Docker Hub (avec SHA GitHub)
        run: docker push dimitridr/yaot:$GITHUB_SHA

      - name: Publication sur Docker Hub (latest)
        run: docker push dimitridr/yaot:latest
